/* tslint:disable */
/* eslint-disable */
/**
 * Wishlist Service
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface WishlistListWishlistItemsRequest
 */
export interface WishlistListWishlistItemsRequest {
    /**
     * 
     * @type {string}
     * @memberof WishlistListWishlistItemsRequest
     */
    'tenantId': string;
    /**
     * 
     * @type {string}
     * @memberof WishlistListWishlistItemsRequest
     */
    'wishlistId': string;
    /**
     * 
     * @type {string}
     * @memberof WishlistListWishlistItemsRequest
     */
    'customerGrn'?: string;
    /**
     * 
     * @type {number}
     * @memberof WishlistListWishlistItemsRequest
     */
    'pageSize'?: number;
    /**
     * 
     * @type {string}
     * @memberof WishlistListWishlistItemsRequest
     */
    'pageToken'?: string;
}
