/* tslint:disable */
/* eslint-disable */
/**
 * Wishlist Service
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface WishlistListWishlistItemsResponse
 */
export interface WishlistListWishlistItemsResponse {
    /**
     * 
     * @type {Array<WishlistWishlistItemResponse>}
     * @memberof WishlistListWishlistItemsResponse
     */
    'wishlistItems'?: Array<WishlistWishlistItemResponse>;
    /**
     * 
     * @type {string}
     * @memberof WishlistListWishlistItemsResponse
     */
    'nextPageToken'?: string;
}
