/* tslint:disable */
/* eslint-disable */
/**
 * Wishlist Service
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface WishlistBulkRemoveItemsFromWishlistsRequest
 */
export interface WishlistBulkRemoveItemsFromWishlistsRequest {
    /**
     * 
     * @type {string}
     * @memberof WishlistBulkRemoveItemsFromWishlistsRequest
     */
    'tenantId': string;
    /**
     * Item GRNs to remove from wishlists. Max 500 items per request.
     * @type {Array<string>}
     * @memberof WishlistBulkRemoveItemsFromWishlistsRequest
     */
    'itemGrns': Array<string>;
    /**
     * Wishlist IDs to remove items from. Max 500 wishlists per request. If not provided, items will be removed from all wishlists.
     * @type {Array<string>}
     * @memberof WishlistBulkRemoveItemsFromWishlistsRequest
     */
    'wishlistIds'?: Array<string>;
}
