/* tslint:disable */
/* eslint-disable */
/**
 * Wishlist Service
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface WishlistSharingRequest
 */
export interface WishlistSharingRequest {
    /**
     * 
     * @type {string}
     * @memberof WishlistSharingRequest
     */
    'wishlistId'?: string;
    /**
     * 
     * @type {WishlistPermission}
     * @memberof WishlistSharingRequest
     */
    'permission'?: WishlistPermission;
    /**
     * 
     * @type {string}
     * @memberof WishlistSharingRequest
     */
    'customerGrn'?: string;
    /**
     * 
     * @type {string}
     * @memberof WishlistSharingRequest
     */
    'customerAggregationId'?: string;
}
