/* tslint:disable */
/* eslint-disable */
/**
 * Wishlist Service
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const WishlistPrivacy = {
    Unknown: 'PRIVACY_UNKNOWN',
    Public: 'PRIVACY_PUBLIC',
    Private: 'PRIVACY_PRIVATE',
    Shared: 'PRIVACY_SHARED'
} as const;
export type WishlistPrivacy = typeof WishlistPrivacy[keyof typeof WishlistPrivacy];


export function WishlistPrivacyFromJSON(json: any): WishlistPrivacy {
    return WishlistPrivacyFromJSONTyped(json, false);
}

export function WishlistPrivacyFromJSONTyped(json: any, ignoreDiscriminator: boolean): WishlistPrivacy {
    return json as WishlistPrivacy;
}

export function WishlistPrivacyToJSON(value?: WishlistPrivacy | null): any {
    return value as any;
}

