/* tslint:disable */
/* eslint-disable */
/**
 * Wishlist Service
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface WishlistCreateWishlistRequest
 */
export interface WishlistCreateWishlistRequest {
    /**
     * 
     * @type {string}
     * @memberof WishlistCreateWishlistRequest
     */
    'tenantId': string;
    /**
     * 
     * @type {WishlistPrivacy}
     * @memberof WishlistCreateWishlistRequest
     */
    'privacy': WishlistPrivacy;
    /**
     * 
     * @type {WishlistLocalizedText}
     * @memberof WishlistCreateWishlistRequest
     */
    'label'?: WishlistLocalizedText;
    /**
     * 
     * @type {WishlistLocalizedText}
     * @memberof WishlistCreateWishlistRequest
     */
    'description'?: WishlistLocalizedText;
    /**
     * If the customer GRN is set on JWT, it will be used as default. Otherwise, it will be used the customer_grn field.
     * @type {string}
     * @memberof WishlistCreateWishlistRequest
     */
    'customerGrn'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof WishlistCreateWishlistRequest
     */
    'isDefault'?: boolean;
}
