/* tslint:disable */
/* eslint-disable */
/**
 * Wishlist Service
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const WishlistPermission = {
    UnknownPermission: 'UNKNOWN_PERMISSION',
    ViewPermission: 'VIEW_PERMISSION',
    EditPermission: 'EDIT_PERMISSION'
} as const;
export type WishlistPermission = typeof WishlistPermission[keyof typeof WishlistPermission];


export function WishlistPermissionFromJSON(json: any): WishlistPermission {
    return WishlistPermissionFromJSONTyped(json, false);
}

export function WishlistPermissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): WishlistPermission {
    return json as WishlistPermission;
}

export function WishlistPermissionToJSON(value?: WishlistPermission | null): any {
    return value as any;
}

