/* tslint:disable */
/* eslint-disable */
/**
 * Wishlist Service
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface WishlistSharingResponse
 */
export interface WishlistSharingResponse {
    /**
     * 
     * @type {string}
     * @memberof WishlistSharingResponse
     */
    'sharingId'?: string;
    /**
     * 
     * @type {string}
     * @memberof WishlistSharingResponse
     */
    'sharingGrn'?: string;
    /**
     * 
     * @type {string}
     * @memberof WishlistSharingResponse
     */
    'wishlistId'?: string;
    /**
     * 
     * @type {WishlistPermission}
     * @memberof WishlistSharingResponse
     */
    'permission'?: WishlistPermission;
    /**
     * 
     * @type {string}
     * @memberof WishlistSharingResponse
     */
    'customerGrn'?: string;
    /**
     * 
     * @type {string}
     * @memberof WishlistSharingResponse
     */
    'customerAggregationId'?: string;
    /**
     * 
     * @type {Date}
     * @memberof WishlistSharingResponse
     */
    'createdAt'?: Date;
    /**
     * 
     * @type {Date}
     * @memberof WishlistSharingResponse
     */
    'updatedAt'?: Date;
}
