/* tslint:disable */
/* eslint-disable */
/**
 * Wishlist Service
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface WishlistGetWishlistBySharedCodeRequest
 */
export interface WishlistGetWishlistBySharedCodeRequest {
    /**
     * 
     * @type {string}
     * @memberof WishlistGetWishlistBySharedCodeRequest
     */
    'tenantId': string;
    /**
     * 
     * @type {string}
     * @memberof WishlistGetWishlistBySharedCodeRequest
     */
    'sharedCode': string;
    /**
     * If the customer GRN is set on JWT, it will be used as default. Otherwise, it will be used the customer_grn field.
     * @type {string}
     * @memberof WishlistGetWishlistBySharedCodeRequest
     */
    'customerGrn'?: string;
}
