/* tslint:disable */
/* eslint-disable */
/**
 * Wishlist Service
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface WishlistUpdateItemInWishlistRequestPayload
 */
export interface WishlistUpdateItemInWishlistRequestPayload {
    /**
     * 
     * @type {string}
     * @memberof WishlistUpdateItemInWishlistRequestPayload
     */
    'preferredQuantity'?: string;
    /**
     * 
     * @type {WishlistLocalizedText}
     * @memberof WishlistUpdateItemInWishlistRequestPayload
     */
    'description'?: WishlistLocalizedText;
    /**
     * 
     * @type {string}
     * @memberof WishlistUpdateItemInWishlistRequestPayload
     */
    'customerGrn'?: string;
}
