/* tslint:disable */
/* eslint-disable */
/**
 * Wishlist Service
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface WishlistWishlistResponse
 */
export interface WishlistWishlistResponse {
    /**
     * 
     * @type {string}
     * @memberof WishlistWishlistResponse
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof WishlistWishlistResponse
     */
    'grn'?: string;
    /**
     * 
     * @type {string}
     * @memberof WishlistWishlistResponse
     */
    'sharedCode'?: string;
    /**
     * 
     * @type {WishlistPrivacy}
     * @memberof WishlistWishlistResponse
     */
    'privacy'?: WishlistPrivacy;
    /**
     * 
     * @type {WishlistLocalizedText}
     * @memberof WishlistWishlistResponse
     */
    'label'?: WishlistLocalizedText;
    /**
     * 
     * @type {WishlistLocalizedText}
     * @memberof WishlistWishlistResponse
     */
    'description'?: WishlistLocalizedText;
    /**
     * 
     * @type {string}
     * @memberof WishlistWishlistResponse
     */
    'customerGrn'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof WishlistWishlistResponse
     */
    'isDefault'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof WishlistWishlistResponse
     */
    'itemsCount'?: string;
    /**
     * 
     * @type {Date}
     * @memberof WishlistWishlistResponse
     */
    'createdAt'?: Date;
    /**
     * 
     * @type {Date}
     * @memberof WishlistWishlistResponse
     */
    'updatedAt'?: Date;
}
