/**
 * Wishlist Service
 * API for managing wishlists
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WishlistUpdateWishlistRequestPayload } from '../models/WishlistUpdateWishlistRequestPayload';
import { HttpFile } from '../http/http';

export class WishlistUpdateWishlistRequest {
    'tenantId': string;
    'id': string;
    'payload': WishlistUpdateWishlistRequestPayload;
    'payloadMask': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "payload",
            "baseName": "payload",
            "type": "WishlistUpdateWishlistRequestPayload",
            "format": ""
        },
        {
            "name": "payloadMask",
            "baseName": "payloadMask",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WishlistUpdateWishlistRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

