/**
 * Wishlist Service
 * API for managing wishlists
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WishlistAreItemsInWishlistsResponsePayload } from '../models/WishlistAreItemsInWishlistsResponsePayload';
import { HttpFile } from '../http/http';

export class WishlistAreItemsInWishlistsResponse {
    'itemGrnMap'?: { [key: string]: WishlistAreItemsInWishlistsResponsePayload; };

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "itemGrnMap",
            "baseName": "itemGrnMap",
            "type": "{ [key: string]: WishlistAreItemsInWishlistsResponsePayload; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WishlistAreItemsInWishlistsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

