/**
 * Wishlist Service
 * API for managing wishlists
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WishlistWishlistItemResponse } from '../models/WishlistWishlistItemResponse';
import { HttpFile } from '../http/http';

export class WishlistListWishlistItemsResponse {
    'wishlistItems'?: Array<WishlistWishlistItemResponse>;
    'nextPageToken'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "wishlistItems",
            "baseName": "wishlistItems",
            "type": "Array<WishlistWishlistItemResponse>",
            "format": ""
        },
        {
            "name": "nextPageToken",
            "baseName": "nextPageToken",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WishlistListWishlistItemsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

