/**
 * Wishlist Service
 * API for managing wishlists
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class WishlistBulkRemoveItemsFromWishlistsRequest {
    'tenantId': string;
    /**
    * Item GRNs to remove from wishlists. Max 500 items per request.
    */
    'itemGrns': Array<string>;
    /**
    * Wishlist IDs to remove items from. Max 500 wishlists per request. If not provided, items will be removed from all wishlists.
    */
    'wishlistIds'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string",
            "format": ""
        },
        {
            "name": "itemGrns",
            "baseName": "itemGrns",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "wishlistIds",
            "baseName": "wishlistIds",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WishlistBulkRemoveItemsFromWishlistsRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

