/**
 * Wishlist Service
 * API for managing wishlists
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WishlistSharingRequest } from '../models/WishlistSharingRequest';
import { HttpFile } from '../http/http';

export class WishlistBulkCreateSharingRequest {
    'tenantId'?: string;
    'sharingRequests'?: Array<WishlistSharingRequest>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string",
            "format": ""
        },
        {
            "name": "sharingRequests",
            "baseName": "sharingRequests",
            "type": "Array<WishlistSharingRequest>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WishlistBulkCreateSharingRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

