/**
 * Wishlist Service
 * API for managing wishlists
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListWishlistsRequestFilter } from '../models/ListWishlistsRequestFilter';
import { HttpFile } from '../http/http';

export class WishlistListWishlistsRequest {
    'tenantId': string;
    'pageSize'?: number;
    'pageToken'?: string;
    'filter'?: ListWishlistsRequestFilter;
    'filterMask'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string",
            "format": ""
        },
        {
            "name": "pageSize",
            "baseName": "pageSize",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "pageToken",
            "baseName": "pageToken",
            "type": "string",
            "format": ""
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "ListWishlistsRequestFilter",
            "format": ""
        },
        {
            "name": "filterMask",
            "baseName": "filterMask",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WishlistListWishlistsRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

