/**
 * Wishlist Service
 * API for managing wishlists
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WishlistWishlistResponse } from '../models/WishlistWishlistResponse';
import { HttpFile } from '../http/http';

export class WishlistListWishlistsResponse {
    'wishlist'?: Array<WishlistWishlistResponse>;
    'nextPageToken'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "wishlist",
            "baseName": "wishlist",
            "type": "Array<WishlistWishlistResponse>",
            "format": ""
        },
        {
            "name": "nextPageToken",
            "baseName": "nextPageToken",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WishlistListWishlistsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

