/**
 * Wishlist Service
 * API for managing wishlists
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WishlistPermission } from '../models/WishlistPermission';
import { HttpFile } from '../http/http';

export class WishlistSharingResponse {
    'sharingId'?: string;
    'sharingGrn'?: string;
    'wishlistId'?: string;
    'permission'?: WishlistPermission;
    'customerGrn'?: string;
    'customerAggregationId'?: string;
    'createdAt'?: Date;
    'updatedAt'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "sharingId",
            "baseName": "sharingId",
            "type": "string",
            "format": ""
        },
        {
            "name": "sharingGrn",
            "baseName": "sharingGrn",
            "type": "string",
            "format": ""
        },
        {
            "name": "wishlistId",
            "baseName": "wishlistId",
            "type": "string",
            "format": ""
        },
        {
            "name": "permission",
            "baseName": "permission",
            "type": "WishlistPermission",
            "format": ""
        },
        {
            "name": "customerGrn",
            "baseName": "customerGrn",
            "type": "string",
            "format": ""
        },
        {
            "name": "customerAggregationId",
            "baseName": "customerAggregationId",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return WishlistSharingResponse.attributeTypeMap;
    }

    public constructor() {
    }
}



