/**
 * Wishlist Service
 * API for managing wishlists
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum WishlistPermission {
    UnknownPermission = 'UNKNOWN_PERMISSION',
    ViewPermission = 'VIEW_PERMISSION',
    EditPermission = 'EDIT_PERMISSION'
}
