/**
 * Wishlist Service
 * API for managing wishlists
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WishlistLocalizedText } from '../models/WishlistLocalizedText';
import { WishlistPrivacy } from '../models/WishlistPrivacy';
import { HttpFile } from '../http/http';

export class WishlistWishlistResponse {
    'id'?: string;
    'grn'?: string;
    'sharedCode'?: string;
    'privacy'?: WishlistPrivacy;
    'label'?: WishlistLocalizedText;
    'description'?: WishlistLocalizedText;
    'customerGrn'?: string;
    'isDefault'?: boolean;
    'itemsCount'?: string;
    'createdAt'?: Date;
    'updatedAt'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "grn",
            "baseName": "grn",
            "type": "string",
            "format": ""
        },
        {
            "name": "sharedCode",
            "baseName": "sharedCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "privacy",
            "baseName": "privacy",
            "type": "WishlistPrivacy",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "WishlistLocalizedText",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "WishlistLocalizedText",
            "format": ""
        },
        {
            "name": "customerGrn",
            "baseName": "customerGrn",
            "type": "string",
            "format": ""
        },
        {
            "name": "isDefault",
            "baseName": "isDefault",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "itemsCount",
            "baseName": "itemsCount",
            "type": "string",
            "format": "uint64"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return WishlistWishlistResponse.attributeTypeMap;
    }

    public constructor() {
    }
}



